In [14]:
import numpy as np
import pandas as pd
country=pd.read_excel(r'Dataset_w6.xlsx')

# 1. Find out how many countries are there in the dataset.

In [51]:
len(country['country'])

196

# 2. Examine the data by using visualizations.

# 3. Find out how many countries with respect to the region are availablein the dataset

In [19]:
pd.value_counts(country['Region'])

WesternAsia          18
EasternAfrica        17
Caribbean            16
WesternAfrica        15
SouthAmerica         12
SouthernEurope       12
South-easternAsia    11
EasternEurope        10
NorthernEurope       10
SouthernAsia          9
MiddleAfrica          9
CentralAmerica        8
WesternEurope         7
EasternAsia           7
SouthernAfrica        5
Polynesia             5
NorthernAfrica        5
Melanesia             5
CentralAsia           5
NorthernAmerica       4
Micronesia            4
Oceania               2
Name: Region, dtype: int64

# 4. On average which region has the highest

# a. GDP per capita (current US$)

In [72]:
gdp=country.groupby(['Region']).mean().sort_values('GDP per capita (current US$)', ascending=False)
gdp.loc[:,['GDP per capita (current US$)']]

                   GDP per capita (current US$)
Region
NorthernAmerica                    57659.000000
WesternEurope                      55387.128571
Oceania                            44823.250000
NorthernEurope                     42098.220000
EasternAsia                        27967.614286
WesternAsia                        17013.938889
Caribbean                          15135.562500
SouthernEurope                     14462.741667
South-easternAsia                  10299.027273
EasternEurope                       9292.490000
Melanesia                           9261.960000
Polynesia                           8686.520000
SouthAmerica                        8499.775000
CentralAmerica                      6348.137500
Micronesia                          5008.300000
CentralAsia                         4329.880000
SouthernAfrica                      4191.900000
NorthernAfrica                      3934.960000
MiddleAfrica                        3928.833333
SouthernAsia                        2968.400000
EasternAfrica                       2088.852941
WesternAfrica                       1013.140000

# b. International trade: Imports (million US$)

In [70]:
imp=country.groupby(['Region']).mean().sort_values('International trade: Imports (million US$)', ascending=False)
imp.loc[:,['International trade: Imports (million US$)']]

                   International trade: Imports (million US$)
Region
NorthernAmerica                                 663552.250000
EasternAsia                                     451995.000000
WesternEurope                                   407498.428571
NorthernEurope                                  113407.200000
Oceania                                         112914.500000
South-easternAsia                                98324.636364
EasternEurope                                    85243.900000
SouthernEurope                                   76666.666667
SouthernAsia                                     58199.333333
CentralAmerica                                   57031.500000
WesternAsia                                      46025.555556
NorthernAfrica                                   35034.400000
SouthAmerica                                     32885.666667
SouthernAfrica                                   18005.600000
CentralAsia                                      12063.400000
WesternAfrica                                     4898.333333
EasternAfrica                                     4726.176471
MiddleAfrica                                      4381.222222
Caribbean                                         3057.312500
Melanesia                                         2896.400000
Polynesia                                          432.000000
Micronesia                                          99.000000

# 5. Find out which region has more consistent with respect to GDP per capita (current US$)

In [74]:
cons=country.groupby(['Region']).std().sort_values('GDP per capita (current US$)')
cons.loc[:,['GDP per capita (current US$)']]

                   GDP per capita (current US$)
Region
WesternAfrica                        815.095399
NorthernAfrica                       974.706575
SouthernAfrica                      2177.551120
SouthernAsia                        2855.708179
EasternAfrica                       3716.131770
CentralAsia                         4152.215490
CentralAmerica                      4180.440883
SouthAmerica                        4273.707394
Micronesia                          4820.669694
MiddleAfrica                        5274.846281
EasternEurope                       5415.488739
Polynesia                           6956.250286
Oceania                             9233.329638
SouthernEurope                      9541.703216
Melanesia                          13855.842686
Caribbean                          14579.371326
South-easternAsia                  16311.810656
WesternAsia                        18812.151459
NorthernEurope                     20671.030185
WesternEurope                      24770.467728
NorthernAmerica                    25749.619445
EasternAsia                        27485.120923